### ISSUE TITLE
no such file or directory, open 'builder-effective-config.yaml'

### ISSUE THREAD

**Issue by ruudboon** [karaggeorge/electron-builder-notarize#10]
I'm not totally sure if this is a bug or that I misconfigured something. Locally notarize runs fine but in github actions I'm experience an issue that results in a missing builder-effective-config.yaml.
See the full log here: https://github.com/ruudboon/tally-blaster/runs/854966767?check_suite_focus=true#step:8:170

**Comment by karaggeorge** [comment]
Hmm, I'm not sure. I haven't used/seen the builder-effective-config.yaml before. If it's working locally, I'm not sure why it would break in CI. Maybe electron-builder does something differently when running in CI?

I'll have to look into it

**Comment by ruudboon** [comment]
Hmm ok. If you could have a quick look it would be great but don't spend too much time. Looks like it's something I messed up.

**Comment by karaggeorge** [comment]
I don't have the time to look into this right now, but for future reference for myself, or anyone else who wants to look into it, the file (and path) are generated here: https://github.com/electron-userland/electron-builder/blob/d5d21da12f5efaf02659ce8d32c48440f6cf91ff/packages/app-builder-lib/src/packager.ts#L354-L359

**Comment by karaggeorge** [comment]
Wait actually right there, in this line: https://github.com/electron-userland/electron-builder/blob/d5d21da12f5efaf02659ce8d32c48440f6cf91ff/packages/app-builder-lib/src/packager.ts#L358

It only generates the file if it's not in CI

**Comment by ruudboon** [comment]
Ahh thnx.Will dive into this. Closing this since it's not related to your work. Thnx again

**Comment by karaggeorge** [comment]
If you find a different area where the appId or the config in general is accessible during the build process let me know, and I can try to update

**Comment by karaggeorge** [comment]
@ruudboon would it help if in the meantime I added support for an env var alternative to appId? So at least you can provide it for GH actions?

**Comment by ruudboon** [comment]
@karaggeorge Yeah that would probably help! On the other hand there must be a reason behind this and I can do manual deployments in the meantime so don't put too much effort into this.

**Comment by karaggeorge** [comment]
@ruudboon https://github.com/ruudboon/tally-blaster/pull/11 😄 Let me know if that works
