### ISSUE TITLE
Update to support new  Xcode 13 notarytool

### ISSUE THREAD

**Issue by delagen** [karaggeorge/electron-builder-notarize#12]
electron-notarize@1.1.0
feat: add support for the new Xcode 13 notarytool

Please update your dependencies

**Comment by WrathofthePast** [comment]
@Delagen, in v1.3, support for Xcode 13's notarytool was added and the electron-notarize dependency was updated to v1.1.1. Can this issue be closed?

**Comment by delagen** [comment]
@WrathofthePast yes. I doesn't issue for me now.
