### ISSUE TITLE
API key support

### ISSUE THREAD

**Issue by samuelmeuli** [karaggeorge/electron-builder-notarize#2]
Thank you for this library, @karaggeorge!

It would be nice if the tool would support the `appleApiKey` and `appleApiIssuer` parameters of the [electron-notarize](https://github.com/electron/electron-notarize) package, i.e. if their values could be provided as environment variables as an alternative to the Apple ID credentials.

Please let me know if you're open to this feature, I could work on a PR :)

**Comment by karaggeorge** [comment]
@samuelmeuli Absolutely. I didn't include them because my use-case didn't need them at the time. Feel free to open a PR. Otherwise I can work on adding it in a few days when I have some time
