### ISSUE TITLE
If you run electron-builder from the vue-cli notarizing fails

### ISSUE THREAD

**Issue by rathboma** [karaggeorge/electron-builder-notarize#6]
electron-builder-notarize looks for the appId in package.json/build/appId.

If you are running electron-builder via [vue-cli-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder), the configuration for the builder is instead stored in `vue.config.js`.

electron-builder-notarize should get the appId from electron-builder directly.

A workaround for now is to add the appId to `build` in package.json

**Comment by oshell** [comment]
this does not work anymore, since putting "build" into package.json is not allowed in newer versions of vue-cli-plugin-electron-builder

I am creating a pull request, which has a fallback for vue-cli-plugin-electron-builder and takes the appId from the created builder config yaml file

**Comment by oshell** [comment]
https://github.com/karaggeorge/electron-builder-notarize/pull/7

**Comment by oshell** [comment]
PR: https://github.com/karaggeorge/electron-builder-notarize/pull/8
